# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'SuperService' do
  pod 'MBProgressHUD'
end

target 'SuperServiceTests' do

end

target 'SuperServiceUITests' do

end

