# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

#use_frameworks!

target 'SuperService' do
  pod 'MBProgressHUD'
  pod 'HexColors'
  pod 'WPMediaPicker', :inhibit_warnings => true
#  pod 'TKAnimatedCheckButton'
end

target 'SuperServiceTests' do

end

target 'SuperServiceUITests' do

end

