# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

#use_frameworks!

target 'SuperService' do
  pod 'JTSImageViewController', :inhibit_warnings => true
  pod 'ChameleonFramework'
  pod 'MJRefresh'
  pod 'JCTagListView'
  pod 'SDWebImage', :inhibit_warnings => true
  pod 'DateTools'
  pod 'SocketRocket', :inhibit_warnings => true
  pod 'AFNetworking', :inhibit_warnings => true
  pod 'XLPagerTabStrip', :inhibit_warnings => true
  pod 'MBProgressHUD'
#  pod 'HexColors'
  pod 'WPMediaPicker', :inhibit_warnings => true
#  pod 'TKAnimatedCheckButton'
end

target 'SuperServiceTests' do

end

target 'SuperServiceUITests' do

end

